/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    categories: Category;
    machines: Machine;
    posts: Post;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    machines: MachinesSelect<false> | MachinesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('it' | 'en') | ('it' | 'en')[];
  globals: {
    home: Home;
    about: About;
    blog: Blog;
    site: Site;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: 'it' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL segment, e.g. "confezionatrici-verticali"
   */
  slug: string;
  description: string;
  heroImage?: (number | null) | Media;
  /**
   * Ordering in menus and on the home carousel (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines".
 */
export interface Machine {
  id: number;
  /**
   * E.g. "FPK 44"
   */
  name: string;
  /**
   * URL segment, e.g. "fpk-44"
   */
  slug: string;
  category: number | Category;
  /**
   * Shown on the category page row
   */
  shortDescription: string;
  /**
   * Large intro paragraph on the product page
   */
  lede: string;
  /**
   * "Technical information" table rows, rendered in order
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * First image doubles as the hero / category-row image
   */
  gallery?: (number | Media)[] | null;
  /**
   * Ordering within the category page (ascending)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  /**
   * Shown on blog cards (clamped to 3 lines) and as the bold lede on the post page
   */
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  date: string;
  cover?: (number | null) | Media;
  /**
   * Optional image carousel below the article
   */
  gallery?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'machines';
        value: number | Machine;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  heroImage?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "machines_select".
 */
export interface MachinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  lede?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  gallery?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  date?: T;
  cover?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    title: string;
    text: string;
    image?: (number | null) | Media;
    ctaLabel: string;
  };
  solutions: {
    eyebrow: string;
    heading: string;
  };
  about: {
    eyebrow: string;
    heading: string;
    /**
     * YouTube/Vimeo embed URL
     */
    videoUrl?: string | null;
  };
  blog: {
    eyebrow: string;
    heading: string;
  };
  contact: {
    heading: string;
    tagline: string;
    sendLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  heroImage?: (number | null) | Media;
  lede: string;
  twoCol: {
    text: string;
    image?: (number | null) | Media;
  };
  /**
   * YouTube/Vimeo embed URL
   */
  videoUrl?: string | null;
  /**
   * Value bullets (wireframe shows 4)
   */
  values?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  heroTitle: string;
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  contact: {
    email: string;
    addressLine1: string;
    addressLine2: string;
  };
  socials?: {
    facebook?: string | null;
    linkedin?: string | null;
    x?: string | null;
    instagram?: string | null;
  };
  /**
   * Supplier/client logos band above the footer
   */
  clientLogos?: (number | Media)[] | null;
  logosHeading: string;
  /**
   * All UI microcopy, localized
   */
  uiStrings: {
    navHome: string;
    navAbout: string;
    navSolutions: string;
    navBlog: string;
    navContacts: string;
    readMore: string;
    viewNow: string;
    relatedArticles: string;
    searchPlaceholder: string;
    technicalInformation: string;
    inquiryTitle: string;
    inquirySubtitle: string;
    inquiryNameLabel: string;
    inquiryContactLabel: string;
    inquiryRequestLabel: string;
    inquiryTermsLabel: string;
    inquirySubmitLabel: string;
    inquirySuccess: string;
    contactAreaLabel: string;
    contactAreaOther: string;
    contactNameLabel: string;
    contactEmailLabel: string;
    contactDescriptionLabel: string;
    footerContactHeading: string;
    /**
     * Use {year} for the current year
     */
    copyright: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        text?: T;
        image?: T;
        ctaLabel?: T;
      };
  solutions?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        videoUrl?: T;
      };
  blog?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  contact?:
    | T
    | {
        heading?: T;
        tagline?: T;
        sendLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heroImage?: T;
  lede?: T;
  twoCol?:
    | T
    | {
        text?: T;
        image?: T;
      };
  videoUrl?: T;
  values?:
    | T
    | {
        text?: T;
        id?: T;
      };
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  heroTitle?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        email?: T;
        addressLine1?: T;
        addressLine2?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        linkedin?: T;
        x?: T;
        instagram?: T;
      };
  clientLogos?: T;
  logosHeading?: T;
  uiStrings?:
    | T
    | {
        navHome?: T;
        navAbout?: T;
        navSolutions?: T;
        navBlog?: T;
        navContacts?: T;
        readMore?: T;
        viewNow?: T;
        relatedArticles?: T;
        searchPlaceholder?: T;
        technicalInformation?: T;
        inquiryTitle?: T;
        inquirySubtitle?: T;
        inquiryNameLabel?: T;
        inquiryContactLabel?: T;
        inquiryRequestLabel?: T;
        inquiryTermsLabel?: T;
        inquirySubmitLabel?: T;
        inquirySuccess?: T;
        contactAreaLabel?: T;
        contactAreaOther?: T;
        contactNameLabel?: T;
        contactEmailLabel?: T;
        contactDescriptionLabel?: T;
        footerContactHeading?: T;
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}